export type ToolCategory =
  | "pdf"
  | "image"
  | "audio"
  | "video"
  | "data"
  | "pdf-utilities"
  | "image-utilities";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  inputFormats: string[];
  outputFormats: string[];
  isPremium?: boolean;
  isNew?: boolean;
  color: string;
}

export const tools: Tool[] = [
  // PDF Conversions
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents with perfect formatting.",
    category: "pdf",
    icon: "FileText",
    inputFormats: ["PDF"],
    outputFormats: ["DOCX"],
    color: "from-blue-500 to-blue-700",
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables and data from PDF into structured Excel spreadsheets.",
    category: "pdf",
    icon: "Table",
    inputFormats: ["PDF"],
    outputFormats: ["XLSX"],
    color: "from-green-500 to-green-700",
  },
  {
    id: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    description: "Convert PDF presentations back to editable PowerPoint slides.",
    category: "pdf",
    icon: "Presentation",
    inputFormats: ["PDF"],
    outputFormats: ["PPTX"],
    color: "from-orange-500 to-orange-700",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert each PDF page to high-quality PNG or JPG images.",
    category: "pdf",
    icon: "Image",
    inputFormats: ["PDF"],
    outputFormats: ["PNG", "JPG"],
    color: "from-purple-500 to-purple-700",
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents to PDF with perfect layout preservation.",
    category: "pdf",
    icon: "FilePlus",
    inputFormats: ["DOCX", "DOC"],
    outputFormats: ["PDF"],
    color: "from-blue-600 to-indigo-700",
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF for easy sharing.",
    category: "pdf",
    icon: "Sheet",  
    inputFormats: ["XLSX", "XLS"],
    outputFormats: ["PDF"],
    color: "from-emerald-500 to-teal-700",
  },
  {
    id: "ppt-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert PowerPoint presentations to PDF instantly.",
    category: "pdf",
    icon: "Monitor",
    inputFormats: ["PPTX", "PPT"],
    outputFormats: ["PDF"],
    color: "from-red-500 to-rose-700",
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert any HTML page or file to a professional PDF document.",
    category: "pdf",
    icon: "Code",
    inputFormats: ["HTML"],
    outputFormats: ["PDF"],
    color: "from-indigo-500 to-violet-700",
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF",
    description: "Render Markdown files as beautiful, formatted PDF documents.",
    category: "pdf",
    icon: "Hash",
    inputFormats: ["MD"],
    outputFormats: ["PDF"],
    color: "from-slate-500 to-slate-700",
  },

  // PDF Utilities
  {
    id: "pdf-merge",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document in seconds.",
    category: "pdf-utilities",
    icon: "Layers",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-pink-500 to-rose-600",
  },
  {
    id: "pdf-split",
    name: "Split PDF",
    description: "Split a PDF into multiple files or extract specific pages.",
    category: "pdf-utilities",
    icon: "Scissors",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-yellow-500 to-amber-600",
  },
  {
    id: "pdf-compress",
    name: "Compress PDF",
    description: "Reduce PDF file size while maintaining quality.",
    category: "pdf-utilities",
    icon: "Archive",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-cyan-500 to-sky-700",
  },
  {
    id: "pdf-watermark",
    name: "Watermark PDF",
    description: "Add custom text or image watermarks to PDF pages.",
    category: "pdf-utilities",
    icon: "Droplets",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-teal-500 to-cyan-700",
  },
  {
    id: "pdf-protect",
    name: "Protect PDF",
    description: "Password protect your PDF files with strong encryption.",
    category: "pdf-utilities",
    icon: "Lock",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-violet-600 to-purple-800",
  },
  {
    id: "pdf-unlock",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files.",
    category: "pdf-utilities",
    icon: "Unlock",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-amber-500 to-orange-600",
  },
  {
    id: "pdf-ocr",
    name: "OCR PDF",
    description: "Extract searchable text from scanned PDFs using OCR technology.",
    category: "pdf-utilities",
    icon: "ScanText",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-lime-500 to-green-700",
    isPremium: true,
  },
  {
    id: "pdf-rearrange",
    name: "Rearrange PDF",
    description: "Drag and drop PDF pages to reorder, delete, or rotate them.",
    category: "pdf-utilities",
    icon: "GripVertical",
    inputFormats: ["PDF"],
    outputFormats: ["PDF"],
    color: "from-fuchsia-500 to-pink-700",
  },

  // Image Utilities
  {
    id: "image-jpg-to-png",
    name: "JPG to PNG",
    description: "Convert JPG images to PNG format with transparency support.",
    category: "image-utilities",
    icon: "Image",
    inputFormats: ["JPG", "JPEG"],
    outputFormats: ["PNG"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-png-to-jpg",
    name: "PNG to JPG",
    description: "Convert PNG images to JPG format quickly.",
    category: "image-utilities",
    icon: "Image",
    inputFormats: ["PNG"],
    outputFormats: ["JPG"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-jpg-to-webp",
    name: "JPG to WebP",
    description: "Convert JPG to modern WebP format for better compression.",
    category: "image-utilities",
    icon: "Zap",
    inputFormats: ["JPG", "JPEG"],
    outputFormats: ["WEBP"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-png-to-webp",
    name: "PNG to WebP",
    description: "Convert PNG to WebP for optimal web performance.",
    category: "image-utilities",
    icon: "Zap",
    inputFormats: ["PNG"],
    outputFormats: ["WEBP"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG vector graphics to raster PNG images.",
    category: "image-utilities",
    icon: "FileCode",
    inputFormats: ["SVG"],
    outputFormats: ["PNG"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to compatible JPG format.",
    category: "image-utilities",
    icon: "Smartphone",
    inputFormats: ["HEIC"],
    outputFormats: ["JPG"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-compress",
    name: "Compress Image",
    description: "Reduce image file size with smart compression algorithms.",
    category: "image-utilities",
    icon: "Minimize2",
    inputFormats: ["JPG", "PNG", "WEBP"],
    outputFormats: ["JPG", "PNG", "WEBP"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-resize",
    name: "Resize Image",
    description: "Change image dimensions while preserving aspect ratio.",
    category: "image-utilities",
    icon: "Maximize2",
    inputFormats: ["JPG", "PNG", "WEBP"],
    outputFormats: ["JPG", "PNG", "WEBP"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "image-crop",
    name: "Crop & Rotate",
    description: "Crop and rotate images with a precision editor.",
    category: "image-utilities",
    icon: "Crop",
    inputFormats: ["JPG", "PNG", "WEBP"],
    outputFormats: ["JPG", "PNG", "WEBP"],
    color: "from-blue-500 to-indigo-600",
  },

  // Audio Conversions
  {
    id: "mp3-to-wav",
    name: "MP3 to WAV",
    description: "Convert MP3 audio to lossless WAV format.",
    category: "audio",
    icon: "Music",
    inputFormats: ["MP3"],
    outputFormats: ["WAV"],
    color: "from-violet-500 to-purple-700",
  },
  {
    id: "wav-to-mp3",
    name: "WAV to MP3",
    description: "Compress WAV audio files to smaller MP3 format.",
    category: "audio",
    icon: "AudioLines",
    inputFormats: ["WAV"],
    outputFormats: ["MP3"],
    color: "from-purple-500 to-indigo-700",
  },
  {
    id: "mp3-to-aac",
    name: "MP3 to AAC",
    description: "Convert MP3 to AAC for better quality at smaller file sizes.",
    category: "audio",
    icon: "Volume2",
    inputFormats: ["MP3"],
    outputFormats: ["AAC"],
    color: "from-fuchsia-500 to-pink-700",
  },
  {
    id: "wav-to-flac",
    name: "WAV to FLAC",
    description: "Convert WAV to lossless FLAC for audiophile-grade audio.",
    category: "audio",
    icon: "Headphones",
    inputFormats: ["WAV"],
    outputFormats: ["FLAC"],
    color: "from-blue-500 to-violet-700",
  },
  {
    id: "audio-compress",
    name: "Audio Bitrate Reducer",
    description: "Reduce audio bitrate to shrink file size for streaming.",
    category: "audio",
    icon: "TrendingDown",
    inputFormats: ["MP3", "WAV", "AAC"],
    outputFormats: ["MP3", "AAC"],
    color: "from-green-500 to-teal-700",
  },

  // Video Conversions
  {
    id: "mp4-to-mkv",
    name: "MP4 to MKV",
    description: "Convert MP4 videos to MKV format with chapter support.",
    category: "video",
    icon: "Video",
    inputFormats: ["MP4"],
    outputFormats: ["MKV"],
    color: "from-red-500 to-rose-700",
    isPremium: true,
  },
  {
    id: "mp4-to-avi",
    name: "MP4 to AVI",
    description: "Convert MP4 to AVI for legacy device compatibility.",
    category: "video",
    icon: "Film",
    inputFormats: ["MP4"],
    outputFormats: ["AVI"],
    color: "from-amber-500 to-yellow-600",
    isPremium: true,
  },
  {
    id: "mov-to-mp4",
    name: "MOV to MP4",
    description: "Convert Apple MOV videos to universal MP4 format.",
    category: "video",
    icon: "Play",
    inputFormats: ["MOV"],
    outputFormats: ["MP4"],
    color: "from-sky-500 to-blue-700",
    isPremium: true,
  },
  {
    id: "compress-video",
    name: "Compress Video",
    description: "Reduce video file size while keeping acceptable quality.",
    category: "video",
    icon: "PackageMinus",
    inputFormats: ["MP4", "MKV", "AVI"],
    outputFormats: ["MP4"],
    color: "from-teal-500 to-emerald-700",
    isPremium: true,
  },
  {
    id: "extract-audio",
    name: "Extract Audio",
    description: "Pull the audio track from any video file as MP3 or WAV.",
    category: "video",
    icon: "AudioWaveform",
    inputFormats: ["MP4", "MKV", "AVI", "MOV"],
    outputFormats: ["MP3", "WAV"],
    color: "from-pink-500 to-fuchsia-700",
    isPremium: true,
  },

  // Data / Developer
  {
    id: "csv-to-xlsx",
    name: "CSV to Excel",
    description: "Convert CSV files to formatted Excel spreadsheets.",
    category: "data",
    icon: "TableProperties",
    inputFormats: ["CSV"],
    outputFormats: ["XLSX"],
    color: "from-green-500 to-emerald-700",
  },
  {
    id: "xlsx-to-csv",
    name: "Excel to CSV",
    description: "Export Excel spreadsheets to universal CSV format.",
    category: "data",
    icon: "FileSpreadsheet",
    inputFormats: ["XLSX"],
    outputFormats: ["CSV"],
    color: "from-lime-500 to-green-700",
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Flatten JSON data arrays into CSV format instantly.",
    category: "data",
    icon: "Braces",
    inputFormats: ["JSON"],
    outputFormats: ["CSV"],
    color: "from-yellow-500 to-orange-600",
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV files to JSON for use in web applications.",
    category: "data",
    icon: "FileJson",
    inputFormats: ["CSV"],
    outputFormats: ["JSON"],
    color: "from-orange-500 to-red-600",
  },
  {
    id: "xml-to-json",
    name: "XML to JSON",
    description: "Transform XML data structures into JSON format.",
    category: "data",
    icon: "Code2",
    inputFormats: ["XML"],
    outputFormats: ["JSON"],
    color: "from-blue-500 to-indigo-700",
  },
  {
    id: "json-to-xml",
    name: "JSON to XML",
    description: "Convert JSON objects to XML for legacy system integration.",
    category: "data",
    icon: "FileCode",
    inputFormats: ["JSON"],
    outputFormats: ["XML"],
    color: "from-indigo-500 to-blue-700",
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON",
    description: "Convert YAML configuration files to JSON format.",
    category: "data",
    icon: "FileCode2",
    inputFormats: ["YAML", "YML"],
    outputFormats: ["JSON"],
    color: "from-violet-500 to-purple-700",
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    description: "Convert JSON data to human-readable YAML format.",
    category: "data",
    icon: "AlignLeft",
    inputFormats: ["JSON"],
    outputFormats: ["YAML"],
    color: "from-purple-500 to-fuchsia-700",
  },
];

export const categories = [
  { id: "pdf", label: "PDF Tools", icon: "FileText", count: tools.filter(t => t.category === "pdf").length },
  { id: "pdf-utilities", label: "PDF Utilities", icon: "Settings", count: tools.filter(t => t.category === "pdf-utilities").length },
  { id: "image", label: "Image Tools", icon: "Image", count: tools.filter(t => t.category === "image").length },
  { id: "image-utilities", label: "Image Utilities", icon: "ImagePlus", count: tools.filter(t => t.category === "image-utilities").length },
  { id: "audio", label: "Audio Tools", icon: "Music", count: tools.filter(t => t.category === "audio").length },
  { id: "video", label: "Video Tools", icon: "Video", count: tools.filter(t => t.category === "video").length },
  { id: "data", label: "Data & Dev", icon: "Code", count: tools.filter(t => t.category === "data").length },
] as const;

export function getToolById(id: string): Tool | undefined {
  return tools.find(t => t.id === id);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter(t => t.category === category);
}
